all: subtask1 subtask2 subtask3 subtask4

subtask1: main.cpp Shape.h
	g++ main.cpp -o exe_1 -std=c++11 -DSUBTASK1

subtask2: main.cpp Shape.h
	g++ main.cpp -o exe_2 -std=c++11 -DSUBTASK2

subtask3: main.cpp Shape.h
	g++ main.cpp -o exe_3 -std=c++11 -DSUBTASK3

subtask4: main.cpp Shape.h
	g++ main.cpp -o exe_4 -std=c++11 -DSUBTASK4

clean:
	rm *.exe